set_property SRC_FILE_INFO {cfile:T:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc rfile:../../../../../uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:T:/15.800000105/fpga_allan/uc_basico/uc_basico.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0.xdc id:3 order:EARLY scoped_inst:u1/microblazer_i/microblaze_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0.xdc id:4 order:EARLY scoped_inst:u1/microblazer_i/microblaze_0_local_memory/dlmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0.xdc id:5 order:EARLY scoped_inst:u1/microblazer_i/microblaze_0_local_memory/ilmb_v10/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0.xdc id:6 order:EARLY scoped_inst:u1/microblazer_i/mdm_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0.xdc id:7 order:EARLY scoped_inst:u1/microblazer_i/clk_wiz_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0.xdc id:8 order:EARLY scoped_inst:u1/microblazer_i/rst_clk_wiz_1_100M} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0.xdc id:9 order:EARLY scoped_inst:u1/microblazer_i/axi_gpio_LED/U0} [current_design]
set_property SRC_FILE_INFO {cfile:t:/15.800000105/fpga_allan/uc_basico/uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1.xdc rfile:../../../../../uc_basico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1.xdc id:10 order:EARLY scoped_inst:u1/microblazer_i/axi_gpio_SW/U0} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {sw[2]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {sw[3]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {sw[4]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {sw[5]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {sw[6]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {sw[7]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {sw[8]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {sw[9]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {sw[10]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {sw[11]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {sw[12]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {sw[13]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {sw[14]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {sw[15]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {led[7]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {led[8]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {led[9]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {led[10]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {led[11]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {led[12]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {led[13]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {led[14]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {led[15]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports btnCpuReset]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btnCpuReset]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_axi_periph]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/mdm_1]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/clk_wiz_1]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/rst_clk_wiz_1_100M]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/axi_gpio_LED]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/axi_gpio_SW]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0/U0]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/dlmb_v10/U0]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/microblaze_0_local_memory/ilmb_v10/U0]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/mdm_1/U0]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/clk_wiz_1/U0]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/axi_gpio_LED/U0]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u1/microblazer_i/axi_gpio_SW/U0]
current_instance u1/microblazer_i/microblaze_0/U0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins MicroBlaze_Core_I/reset_temp_reg*/D]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins u1/microblazer_i/microblaze_0_local_memory/dlmb_v10/U0/SYS_Rst]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins u1/microblazer_i/microblaze_0_local_memory/ilmb_v10/U0/SYS_Rst]
current_instance u1/microblazer_i/mdm_1/U0
set_property src_info {type:SCOPED_XDC file:6 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK [get_pins Use*.BSCAN*/DRCK]
set_property src_info {type:SCOPED_XDC file:6 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE [get_pins Use*.BSCAN*/UPDATE]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK]
set_property src_info {type:SCOPED_XDC file:6 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE]
set_property src_info {type:SCOPED_XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -logically_exclusive -group [get_clocks u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/DRCK] -group [get_clocks u1/microblazer_i/mdm_1/U0/Use_E2.BSCANE2_I/UPDATE]
set_property src_info {type:SCOPED_XDC file:7 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKFBOUT -source [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 20.000 40.000} -add -master_clock clk [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKOUT0 -source [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 45.000 90.000} -add -master_clock clk [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:SCOPED_XDC file:8 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins u1/microblazer_i/rst_clk_wiz_1_100M/ext_reset_in]
set_property src_info {type:SCOPED_XDC file:9 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[15]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[0]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[1]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[2]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[3]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[4]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[5]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[6]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[7]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[8]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[9]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[10]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[11]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[12]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[13]/D} {u1/microblazer_i/axi_gpio_LED/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[14]/D}]]
set_property src_info {type:SCOPED_XDC file:10 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[15]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[0]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[1]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[2]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[3]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[4]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[5]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[6]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[7]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[8]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[9]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[10]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[11]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[12]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[13]/D} {u1/microblazer_i/axi_gpio_SW/U0/gpio_core_1/Not_Dual.INPUT_DOUBLE_REGS3/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.s_level_out_bus_d1_cdc_to_reg[14]/D}]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKFBOUT_1 -source [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 20.000 40.000} -add -master_clock sys_clk_pin [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKOUT0_1 -source [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 45.000 90.000} -add -master_clock sys_clk_pin [get_pins u1/microblazer_i/clk_wiz_1/U0/mmcm_adv_inst/CLKOUT0]
