# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/15.800000105/fpga_allan/LED7SEG/LED7SEG.srcs/sources_1/new/aula4.vhd
read_xdc T:/15.800000105/fpga_allan/LED7SEG/LED7SEG.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc
set_property used_in_implementation false [get_files T:/15.800000105/fpga_allan/LED7SEG/LED7SEG.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/15.800000105/fpga_allan/LED7SEG/LED7SEG.cache/wt [current_project]
set_property parent.project_dir T:/15.800000105/fpga_allan/LED7SEG [current_project]
synth_design -top aula4 -part xc7a100tcsg324-1
write_checkpoint aula4.dcp
report_utilization -file aula4_utilization_synth.rpt -pb aula4_utilization_synth.pb
